my_gather = ["Total Debt/Equity",
             'Trailing P/E',
             'Price/Sales',
             'Price/Book',
             'Profit Margin',
             'Operating Margin',
             'Return on Assets',
             'Return on Equity',
             'Revenue Per Share',
             'Market Cap',
             'Enterprise Value',
             'Forward P/E',
             'PEG Ratio',
             'Enterprise Value/Revenue',
             'Enterprise Value/EBITDA',
             'Revenue',
             'Gross Profit',
             'EBITDA',
             'Net Income Avl to Common ',
             'Diluted EPS',
             'Earnings Growth',
             'Revenue Growth',
             'Total Cash',
             'Total Cash Per Share',
             'Total Debt',
             'Current Ratio',
             'Book Value Per Share',
             'Cash Flow',
             'Beta',
             'Held by Insiders',
             'Held by Institutions',
             'Shares Short (as of',
             'Short Ratio',
             'Short % of Float',
             'Shares Short (prior ']

my_df_cols = ['Date',
              'Unix',
              'Ticker',
              'Price',
              'stock_p_change',
              'SP500',
              'sp500_p_change',
              'Difference',
              'DE Ratio',
              'Trailing P/E',
              'Price/Sales',
              'Price/Book',
              'Profit Margin',
              'Operating Margin',
              'Return on Assets',
              'Return on Equity',
              'Revenue Per Share',
              'Market Cap',
              'Enterprise Value',
              'Forward P/E',
              'PEG Ratio',
              'Enterprise Value/Revenue',
              'Enterprise Value/EBITDA',
              'Revenue',
              'Gross Profit',
              'EBITDA',
              'Net Income Avl to Common ',
              'Diluted EPS',
              'Earnings Growth',
              'Revenue Growth',
              'Total Cash',
              'Total Cash Per Share',
              'Total Debt',
              'Current Ratio',
              'Book Value Per Share',
              'Cash Flow',
              'Beta',
              'Held by Insiders',
              'Held by Institutions',
              'Shares Short (as of',
              'Short Ratio',
              'Short % of Float',
              'Shares Short (prior ',
              'Status']

my_df_cols_1y = ['Date',
                 'Unix',
                 'Ticker',
                 'Price',
                 'Price_1y',
                 'stock_p_change',
                 'SP500',
                 'SP500_1y',
                 'sp500_p_change',
                 'Difference',
                 'DE Ratio',
                 'Trailing P/E',
                 'Price/Sales',
                 'Price/Book',
                 'Profit Margin',
                 'Operating Margin',
                 'Return on Assets',
                 'Return on Equity',
                 'Revenue Per Share',
                 'Market Cap',
                 'Enterprise Value',
                 'Forward P/E',
                 'PEG Ratio',
                 'Enterprise Value/Revenue',
                 'Enterprise Value/EBITDA',
                 'Revenue',
                 'Gross Profit',
                 'EBITDA',
                 'Net Income Avl to Common ',
                 'Diluted EPS',
                 'Earnings Growth',
                 'Revenue Growth',
                 'Total Cash',
                 'Total Cash Per Share',
                 'Total Debt',
                 'Current Ratio',
                 'Book Value Per Share',
                 'Cash Flow',
                 'Beta',
                 'Held by Insiders',
                 'Held by Institutions',
                 'Shares Short (as of',
                 'Short Ratio',
                 'Short % of Float',
                 'Shares Short (prior ',
                 'Status']

FEATURES = ['DE Ratio',
            'Trailing P/E',
            'Price/Sales',
            'Price/Book',
            'Profit Margin',
            'Operating Margin',
            'Return on Assets',
            'Return on Equity',
            'Revenue Per Share',
            'Market Cap',
            'Enterprise Value',
            'Forward P/E',
            'PEG Ratio',
            'Enterprise Value/Revenue',
            'Enterprise Value/EBITDA',
            'Revenue',
            'Gross Profit',
            'EBITDA',
            'Net Income Avl to Common ',
            'Diluted EPS',
            'Earnings Growth',
            'Revenue Growth',
            'Total Cash',
            'Total Cash Per Share',
            'Total Debt',
            'Current Ratio',
            'Book Value Per Share',
            'Cash Flow',
            'Beta',
            'Held by Insiders',
            'Held by Institutions',
            'Shares Short (as of',
            'Short Ratio',
            'Short % of Float',
            'Shares Short (prior ']
